window.WORLD_CUP_GROUP_STAGE_MATCHES = [
  { id: 1, group: "A", teamA: "México", teamB: "África do Sul", date: "11/06/2026", time: "13:00", stadium: "Estadio Azteca", city: "Cidade do México" },
  { id: 2, group: "A", teamA: "Coreia do Sul", teamB: "Tchéquia", date: "11/06/2026", time: "20:00", stadium: "Estadio Akron", city: "Guadalajara" },
  { id: 3, group: "B", teamA: "Canadá", teamB: "Bósnia e Herzegovina", date: "12/06/2026", time: "15:00", stadium: "BMO Field", city: "Toronto" },
  { id: 4, group: "D", teamA: "Estados Unidos", teamB: "Paraguai", date: "12/06/2026", time: "18:00", stadium: "SoFi Stadium", city: "Los Angeles" },
  { id: 5, group: "C", teamA: "Haiti", teamB: "Escócia", date: "13/06/2026", time: "21:00", stadium: "Gillette Stadium", city: "Boston" },
  { id: 6, group: "D", teamA: "Austrália", teamB: "Türkiye", date: "13/06/2026", time: "21:00", stadium: "BC Place", city: "Vancouver" },
  { id: 7, group: "C", teamA: "Brasil", teamB: "Marrocos", date: "13/06/2026", time: "18:00", stadium: "MetLife Stadium", city: "Nova York/Nova Jersey" },
  { id: 8, group: "B", teamA: "Qatar", teamB: "Suíça", date: "13/06/2026", time: "12:00", stadium: "Levi's Stadium", city: "Área da Baía de San Francisco" },
  { id: 9, group: "E", teamA: "Costa do Marfim", teamB: "Equador", date: "14/06/2026", time: "19:00", stadium: "Lincoln Financial Field", city: "Philadelphia" },
  { id: 10, group: "E", teamA: "Alemanha", teamB: "Curaçao", date: "14/06/2026", time: "12:00", stadium: "NRG Stadium", city: "Houston" },
  { id: 11, group: "F", teamA: "Holanda", teamB: "Japão", date: "14/06/2026", time: "15:00", stadium: "AT&T Stadium", city: "Dallas" },
  { id: 12, group: "F", teamA: "Suécia", teamB: "Tunísia", date: "14/06/2026", time: "20:00", stadium: "Estadio BBVA", city: "Monterrey" },
  { id: 13, group: "H", teamA: "Arábia Saudita", teamB: "Uruguai", date: "15/06/2026", time: "18:00", stadium: "Hard Rock Stadium", city: "Miami" },
  { id: 14, group: "H", teamA: "Espanha", teamB: "Cabo Verde", date: "15/06/2026", time: "12:00", stadium: "Mercedes-Benz Stadium", city: "Atlanta" },
  { id: 15, group: "G", teamA: "Irã", teamB: "Nova Zelândia", date: "15/06/2026", time: "18:00", stadium: "SoFi Stadium", city: "Los Angeles" },
  { id: 16, group: "G", teamA: "Bélgica", teamB: "Egito", date: "15/06/2026", time: "12:00", stadium: "Lumen Field", city: "Seattle" },
  { id: 17, group: "I", teamA: "França", teamB: "Senegal", date: "16/06/2026", time: "15:00", stadium: "MetLife Stadium", city: "Nova York/Nova Jersey" },
  { id: 18, group: "I", teamA: "Iraque", teamB: "Noruega", date: "16/06/2026", time: "18:00", stadium: "Gillette Stadium", city: "Boston" },
  { id: 19, group: "J", teamA: "Argentina", teamB: "Argélia", date: "16/06/2026", time: "20:00", stadium: "Arrowhead Stadium", city: "Kansas City" },
  { id: 20, group: "J", teamA: "Áustria", teamB: "Jordânia", date: "16/06/2026", time: "21:00", stadium: "Levi's Stadium", city: "Área da Baía de San Francisco" },
  { id: 21, group: "L", teamA: "Gana", teamB: "Panamá", date: "17/06/2026", time: "19:00", stadium: "BMO Field", city: "Toronto" },
  { id: 22, group: "L", teamA: "Inglaterra", teamB: "Croácia", date: "17/06/2026", time: "15:00", stadium: "AT&T Stadium", city: "Dallas" },
  { id: 23, group: "K", teamA: "Portugal", teamB: "RD Congo", date: "17/06/2026", time: "12:00", stadium: "NRG Stadium", city: "Houston" },
  { id: 24, group: "K", teamA: "Uzbequistão", teamB: "Colômbia", date: "17/06/2026", time: "20:00", stadium: "Estadio Azteca", city: "Cidade do México" },
  { id: 25, group: "A", teamA: "Tchéquia", teamB: "África do Sul", date: "18/06/2026", time: "12:00", stadium: "Mercedes-Benz Stadium", city: "Atlanta" },
  { id: 26, group: "B", teamA: "Suíça", teamB: "Bósnia e Herzegovina", date: "18/06/2026", time: "12:00", stadium: "SoFi Stadium", city: "Los Angeles" },
  { id: 27, group: "B", teamA: "Canadá", teamB: "Qatar", date: "18/06/2026", time: "15:00", stadium: "BC Place", city: "Vancouver" },
  { id: 28, group: "A", teamA: "México", teamB: "Coreia do Sul", date: "18/06/2026", time: "19:00", stadium: "Estadio Akron", city: "Guadalajara" },
  { id: 29, group: "C", teamA: "Brasil", teamB: "Haiti", date: "19/06/2026", time: "21:00", stadium: "Lincoln Financial Field", city: "Philadelphia" },
  { id: 30, group: "C", teamA: "Escócia", teamB: "Marrocos", date: "19/06/2026", time: "18:00", stadium: "Gillette Stadium", city: "Boston" },
  { id: 31, group: "D", teamA: "Türkiye", teamB: "Paraguai", date: "19/06/2026", time: "20:00", stadium: "Levi's Stadium", city: "Área da Baía de San Francisco" },
  { id: 32, group: "D", teamA: "Estados Unidos", teamB: "Austrália", date: "19/06/2026", time: "12:00", stadium: "Lumen Field", city: "Seattle" },
  { id: 33, group: "E", teamA: "Alemanha", teamB: "Costa do Marfim", date: "20/06/2026", time: "16:00", stadium: "BMO Field", city: "Toronto" },
  { id: 34, group: "E", teamA: "Equador", teamB: "Curaçao", date: "20/06/2026", time: "19:00", stadium: "Arrowhead Stadium", city: "Kansas City" },
  { id: 35, group: "F", teamA: "Holanda", teamB: "Suécia", date: "20/06/2026", time: "12:00", stadium: "NRG Stadium", city: "Houston" },
  { id: 36, group: "F", teamA: "Tunísia", teamB: "Japão", date: "20/06/2026", time: "22:00", stadium: "Estadio BBVA", city: "Monterrey" },
  { id: 37, group: "H", teamA: "Uruguai", teamB: "Cabo Verde", date: "21/06/2026", time: "18:00", stadium: "Hard Rock Stadium", city: "Miami" },
  { id: 38, group: "H", teamA: "Espanha", teamB: "Arábia Saudita", date: "21/06/2026", time: "12:00", stadium: "Mercedes-Benz Stadium", city: "Atlanta" },
  { id: 39, group: "G", teamA: "Bélgica", teamB: "Irã", date: "21/06/2026", time: "12:00", stadium: "SoFi Stadium", city: "Los Angeles" },
  { id: 40, group: "G", teamA: "Nova Zelândia", teamB: "Egito", date: "21/06/2026", time: "18:00", stadium: "BC Place", city: "Vancouver" },
  { id: 41, group: "I", teamA: "Noruega", teamB: "Senegal", date: "22/06/2026", time: "20:00", stadium: "MetLife Stadium", city: "Nova York/Nova Jersey" },
  { id: 42, group: "I", teamA: "França", teamB: "Iraque", date: "22/06/2026", time: "17:00", stadium: "Lincoln Financial Field", city: "Philadelphia" },
  { id: 43, group: "J", teamA: "Argentina", teamB: "Áustria", date: "22/06/2026", time: "12:00", stadium: "AT&T Stadium", city: "Dallas" },
  { id: 44, group: "J", teamA: "Jordânia", teamB: "Argélia", date: "22/06/2026", time: "20:00", stadium: "Levi's Stadium", city: "Área da Baía de San Francisco" },
  { id: 45, group: "L", teamA: "Inglaterra", teamB: "Gana", date: "23/06/2026", time: "16:00", stadium: "Gillette Stadium", city: "Boston" },
  { id: 46, group: "L", teamA: "Panamá", teamB: "Croácia", date: "23/06/2026", time: "19:00", stadium: "BMO Field", city: "Toronto" },
  { id: 47, group: "K", teamA: "Portugal", teamB: "Uzbequistão", date: "23/06/2026", time: "12:00", stadium: "NRG Stadium", city: "Houston" },
  { id: 48, group: "K", teamA: "Colômbia", teamB: "RD Congo", date: "23/06/2026", time: "20:00", stadium: "Estadio Akron", city: "Guadalajara" },
  { id: 49, group: "C", teamA: "Escócia", teamB: "Brasil", date: "24/06/2026", time: "18:00", stadium: "Hard Rock Stadium", city: "Miami" },
  { id: 50, group: "C", teamA: "Marrocos", teamB: "Haiti", date: "24/06/2026", time: "18:00", stadium: "Mercedes-Benz Stadium", city: "Atlanta" },
  { id: 51, group: "B", teamA: "Suíça", teamB: "Canadá", date: "24/06/2026", time: "12:00", stadium: "BC Place", city: "Vancouver" },
  { id: 52, group: "B", teamA: "Bósnia e Herzegovina", teamB: "Qatar", date: "24/06/2026", time: "12:00", stadium: "Lumen Field", city: "Seattle" },
  { id: 53, group: "A", teamA: "Tchéquia", teamB: "México", date: "24/06/2026", time: "19:00", stadium: "Estadio Azteca", city: "Cidade do México" },
  { id: 54, group: "A", teamA: "África do Sul", teamB: "Coreia do Sul", date: "24/06/2026", time: "19:00", stadium: "Estadio BBVA", city: "Monterrey" },
  { id: 55, group: "E", teamA: "Curaçao", teamB: "Costa do Marfim", date: "25/06/2026", time: "16:00", stadium: "Lincoln Financial Field", city: "Philadelphia" },
  { id: 56, group: "E", teamA: "Equador", teamB: "Alemanha", date: "25/06/2026", time: "16:00", stadium: "MetLife Stadium", city: "Nova York/Nova Jersey" },
  { id: 57, group: "F", teamA: "Japão", teamB: "Suécia", date: "25/06/2026", time: "18:00", stadium: "AT&T Stadium", city: "Dallas" },
  { id: 58, group: "F", teamA: "Tunísia", teamB: "Holanda", date: "25/06/2026", time: "18:00", stadium: "Arrowhead Stadium", city: "Kansas City" },
  { id: 59, group: "D", teamA: "Türkiye", teamB: "Estados Unidos", date: "25/06/2026", time: "19:00", stadium: "SoFi Stadium", city: "Los Angeles" },
  { id: 60, group: "D", teamA: "Paraguai", teamB: "Austrália", date: "25/06/2026", time: "19:00", stadium: "Levi's Stadium", city: "Área da Baía de San Francisco" },
  { id: 61, group: "I", teamA: "Noruega", teamB: "França", date: "26/06/2026", time: "15:00", stadium: "Gillette Stadium", city: "Boston" },
  { id: 62, group: "I", teamA: "Senegal", teamB: "Iraque", date: "26/06/2026", time: "15:00", stadium: "BMO Field", city: "Toronto" },
  { id: 63, group: "G", teamA: "Egito", teamB: "Irã", date: "26/06/2026", time: "20:00", stadium: "Lumen Field", city: "Seattle" },
  { id: 64, group: "G", teamA: "Nova Zelândia", teamB: "Bélgica", date: "26/06/2026", time: "20:00", stadium: "BC Place", city: "Vancouver" },
  { id: 65, group: "H", teamA: "Cabo Verde", teamB: "Arábia Saudita", date: "26/06/2026", time: "19:00", stadium: "NRG Stadium", city: "Houston" },
  { id: 66, group: "H", teamA: "Uruguai", teamB: "Espanha", date: "26/06/2026", time: "18:00", stadium: "Estadio Akron", city: "Guadalajara" },
  { id: 67, group: "L", teamA: "Panamá", teamB: "Inglaterra", date: "27/06/2026", time: "17:00", stadium: "MetLife Stadium", city: "Nova York/Nova Jersey" },
  { id: 68, group: "L", teamA: "Croácia", teamB: "Gana", date: "27/06/2026", time: "17:00", stadium: "Lincoln Financial Field", city: "Philadelphia" },
  { id: 69, group: "J", teamA: "Argélia", teamB: "Áustria", date: "27/06/2026", time: "21:00", stadium: "Arrowhead Stadium", city: "Kansas City" },
  { id: 70, group: "J", teamA: "Jordânia", teamB: "Argentina", date: "27/06/2026", time: "21:00", stadium: "AT&T Stadium", city: "Dallas" },
  { id: 71, group: "K", teamA: "Colômbia", teamB: "Portugal", date: "27/06/2026", time: "19:30", stadium: "Hard Rock Stadium", city: "Miami" },
  { id: 72, group: "K", teamA: "RD Congo", teamB: "Uzbequistão", date: "27/06/2026", time: "19:30", stadium: "Mercedes-Benz Stadium", city: "Atlanta" }
];